services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 1234
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dictionary
    ports:
      - '6000:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
  libre_translate:
    container_name: libre_translate
    image: 'libretranslate/libretranslate:latest'
    ports:
      - '5000:5000'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
    name: postgres-network

volumes:
  postgres: {}
  pgadmin: {}
