services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: local-network
      JWT_SECRET: ${DEV_JWT_SECRET}
      DB_URL: ${DEV_DB_URL}
      DB_USER: ${DEV_DB_USER}
      DB_PASS: ${DEV_DB_PASS}
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '8081:80'
    networks:
      - backend


volumes:
  postgres_data: {}
  pgadmin: {}

networks:
  backend:
    name: backend
    driver: bridge
