services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 1234
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dictionary
    ports:
      - '6000:5432'
#  postgres-test:
#    image: 'postgres:latest'
#    environment:
#      POSTGRES_USER: 1234
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: dictionary
#    ports:
#      - '6001:5432'
