services:
  postgres:
    container_name: postgres_dev
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 1234
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dictionary
    ports:
      - '6000:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
  libre_translate:
    container_name: libre_translate_dev
    image: 'libretranslate/libretranslate:latest'
    ports:
      - '5000:5000'
  ollama:
    container_name: ollama_dev
    image: ollama/ollama:rocm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
    name: postgres-network

volumes:
  ollama: {}
  postgres: {}
  pgadmin: {}
