spring:
  mvc:
    trailing-slash:
      match: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  application:
    name: "dictionary"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
translation:
  libreTranslate:
    base:
      url: "/translate"
gg:
  jte:
    development-mode: false
    usePrecompiledTemplates: true
    precompiled: gg.jte.generated.precompiled
logging:
  level:
    gg:
      jte: DEBUG
    org.springframework.web.servlet.view: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

server:
  compression:
    enabled: true
    min-response-size: 2048

