spring:
  application:
    name: "dictionary"
  datasource:
    url: "jdbc:postgresql://localhost:6000/dictionary"
    username: "1234"
    password: "1234"
gg:
  jte:
    templateLocation: src/main/jte
    templateSuffix: .jte
    developmentMode: true