spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    trailing-slash:
      match: true
  security:
    jwt:
      public: ${JWT_PUBLIC}
      private: ${JWT_PRIVATE}
  application:
    name: "dictionary"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
translation:
  libreTranslate:
    base:
      url: "/translate"

ollama:
  api:
    baseUrl: "http://localhost:11434"
gg:
  jte:
    templateLocation: src/main/jte
    templateSuffix: .jte
    developmentMode: true
    usePrecompiledTemplates: false
flyway:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASS}
logging:
  level:
    org:
      springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.security.web.FilterChainProxy: DEBUG
server:
  compression:
    enabled: true
    min-response-size: 2048
