spring:
  application:
    name: "dictionary"
  datasource:
    url: "jdbc:postgresql://localhost:6000/dictionary"
    username: "1234"
    password: "1234"
gg:
  jte:
    templateLocation: src/main/jte
    templateSuffix: .jte
    developmentMode: true
logging:
  level:
    org:
      springframework.jdbc.core: DEBUG
      springframework.jdbc.core.JdbcTemplate: DEBUG
      springframework.jdbc.core.StatementCreatorUtils: TRACE
      springframework:
        web:
          - "DEBUG"
server:
  compression:
    enabled: true
    min-response-size: 2048
