spring:
  mvc:
    trailing-slash:
      match: true
  security:
    jwt:
      public: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw6QAOU3eL9JT8M81wurzA+69YP6mBidtAUkR8dN9W//CPLSvihvDZwfseFSOMbcNBK3B80LuR0sWYFnaL3lIaj6tteCK9LgTIx4FT3sIgyNqoFnpCDWGXddEZA50oHOnC+u3DIPKJ3f9Tr86U6iSJDBye+bIiQM9a/uqZhZr38P1TOJ9EnVaOio+ipAXS67QMrtxSHkWU66CCcKz815h83oWVPjmXHU/JqXY048CEVTrRDCj6ggvl3QmfKx8bhlAEgV29N4hSpc6XatJR2XEWHQIAAed7804Ckzn8FP0QQ3vAiWlBjPLHyAfxUepdJyRMH8bCVZNVLpv3AhSL+4ZgwIDAQAB"
      private: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDpAA5Td4v0lPwzzXC6vMD7r1g/qYGJ20BSRHx031b/8I8tK+KG8NnB+x4VI4xtw0ErcHzQu5HSxZgWdoveUhqPq214Ir0uBMjHgVPewiDI2qgWekINYZd10RkDnSgc6cL67cMg8ond/1OvzpTqJIkMHJ75siJAz1r+6pmFmvfw/VM4n0SdVo6Kj6KkBdLrtAyu3FIeRZTroIJwrPzXmHzehZU+OZcdT8mpdjTjwIRVOtEMKPqCC+XdCZ8rHxuGUASBXb03iFKlzpdq0lHZcRYdAgAB53vzTgKTOfwU/RBDe8CJaUGM8sfIB/FR6l0nJEwfxsJVk1Uum/cCFIv7hmDAgMBAAECggEAFVJd3eDxKqgTEucaVlxx0Mdnp1cJdBk+5Yl3pbHlcy3cFu6gRP6CnMt9x517g8qN5ikjvqXYPzfdP/H69/qRXFbpaq2Gp2YaW9TtQjzH8Dbfa4tw/L6MntSTtQ3oQwZnucJeSERit0t59Wec7Totdzk6eOtthpUuUAL1Drw51ICfWZLeFDCXCfiRxYlKxlQBcQJo7Yobj4wbukRrOUJJ2eMTVtECmv+8F0oiR+vpPm6Je5B+5FpmfdYm3gRbiSHFMkhAknicWuPdhZd2g3D5LqwipI6bucnRlKtCDEX5L+0PaY3yefokT9AJNhtkZ9K6OFqZwANPoONmeANpEW5rwQKBgQDzs4TahUmDfxbK57i6LOdWEhIqeOJnZZ9OIvaqKg0lWtIQRffKAh45XJnEpsPfpXe3QO2aemAVZDBghX8VJtL5iZ51SEj81r4wYTebllLN9m3WWYuDSqnhf6hjaGBOH9OWrIGT8AfGXmq+TEA9moG/PJWbRILTqt/+7HPOF4pBQwKBgQDNg5Dv4Mi6YLJv7DUGbrtxRizM4QGmSVelpmJSvGnyF8WaW58fQXixWFlVUMD8PM/IksXuweKaChhlvgBri0FjpwNaiS6otW4uC2YARk1FyQETP+WFx6bvliK+pbxK7xgjzeUngiQffgxZmbHwLBH3NRjJ4rdH1hS+Mikc91giwQKBgDlD7ewLdgLYUlrLqLTW6GVpSauBTHJPhuetf5js2Ln2ZXY9esSVStTf1aJILa7YCxGcyDiMmRdtu5ByzjICNYE9vWaB3eTL8VUdAxwkbsDHL3g3AnmPievbO45gcIDrKaU2VByXQrxyY1LkSBQxwltVuTILH1LtzETy+yNqlKpRAoGABrRWFB1HLx1cdN5F1JHkN4vMhlqIzT3zSAonhv9yjV1NKv32MPTX1SFGuMvLn+7z8F0pa+KTW+ccaKVMKjX+yht2totnJEXW9FWW3Edu2en2yQP6nuSmg4ZoV8PcYq1uIizjXuiV+RkJmhqzfVxSsbffuSZWSFepkZLdWH6RN4ECgYAN+rKT+M15tTD7le19XhY5/ur+BEfCr3qedshVcu864/V/7RJSBfCNS3sb0zuxwU1PUF2xMVTWUeCEme3hd/4FpgX0k7xzD4OlHmQTOhhblRAsqjDX58OmhwhQTmze8WazJSx14Wg15wZOghBm4NYuFmdfgWiBGpBuQ9s8OYYYIg"
  application:
    name: "dictionary"
  datasource:
    url: "jdbc:postgresql://localhost:6000/dictionary"
    username: "1234"
    password: "1234"
translation:
  libreTranslate:
    base:
      url: "/translate"

gg:
  jte:
    templateLocation: src/main/jte
    templateSuffix: .jte
    developmentMode: true
flyway:
  url: "jdbc:postgresql://localhost:6000/dictionary"
  user: "1234"
  password: "1234"
logging:
  level:
    org:
      springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.security.web.FilterChainProxy: DEBUG
server:
  compression:
    enabled: true
    min-response-size: 2048
